ALTER SERVER ROLE [sysadmin] ADD MEMBER [DESKTOP-PFLGU3I\Igor];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\SQLWriter];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\Winmgmt];

